customhost = "employee.c9pulvddhfux.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "kelvineeweikeong-employee"
customregion = "us-east-1"
